/** Concept words a spymaster reaches for. The fallback proposer samples from these when no LLM is configured. */
export const CLUE_WORDS: readonly string[] = [
  "animal", "aquatic", "arctic", "army", "art", "athlete", "autumn", "baby", "bakery", "ballet",
  "battle", "beauty", "bedroom", "beverage", "bicycle", "birthday", "body", "breakfast", "brewery", "building",
  "camping", "canada", "candy", "capital", "carnival", "cartoon", "cattle", "celebration", "ceremony", "chemistry",
  "childhood", "china", "chocolate", "christmas", "cinema", "circus", "city", "classroom", "climate", "clothing",
  "coffee", "cold", "colony", "comedy", "communication", "computer", "construction", "container", "cooking", "cosmetics",
  "country", "cowboy", "craft", "crime", "crop", "crystal", "currency", "dairy", "danger", "dark",
  "dawn", "decoration", "dentist", "dessert", "detective", "dinner", "dinosaur", "disaster", "dream", "dungeon",
  "egypt", "electricity", "emergency", "energy", "england", "entertainment", "equipment", "europe", "evening", "explosion",
  "fabric", "factory", "fairy", "family", "fantasy", "fashion", "fast", "festival", "fiction", "finance",
  "fishing", "fitness", "flight", "flower", "food", "football", "france", "freedom", "frozen", "furniture",
  "gambling", "geography", "geometry", "gift", "glass", "government", "gravity", "greece", "grocery", "halloween",
  "harvest", "hawaii", "health", "heat", "hero", "highway", "hiking", "history", "holiday", "hollywood",
  "home", "horror", "hunting", "hygiene", "india", "industry", "insect", "instrument", "internet", "invention",
  "italy", "japan", "jewelry", "journey", "jungle", "justice", "kingdom", "kitchen", "laboratory", "landscape",
  "laundry", "law", "legend", "liquid", "literature", "luck", "luxury", "machine", "magic", "mail",
  "mammal", "marine", "market", "marriage", "mathematics", "meat", "medicine", "medieval", "metal", "mexico",
  "military", "mining", "money", "monster", "morning", "motion", "mountain", "movie", "museum", "mythology",
  "nature", "navy", "newspaper", "noise", "nutrition", "occupation", "office", "olympics", "opera", "orchestra",
  "outdoors", "pain", "painting", "party", "pet", "photography", "physics", "picnic", "pioneer", "pirate",
  "planet", "plumbing", "poetry", "poison", "police", "politics", "pollution", "power", "prison", "radio",
  "railway", "rainforest", "religion", "reptile", "restaurant", "revolution", "romance", "rome", "royalty", "safari",
  "sailing", "science", "sculpture", "sea", "season", "security", "shape", "shelter", "shipping", "shopping",
  "sickness", "signal", "sleep", "software", "sound", "space", "speed", "sport", "stationery", "structure",
  "summer", "surgery", "sweet", "technology", "television", "temperature", "texas", "theater", "time", "tool",
  "toy", "traffic", "transport", "treasure", "tropical", "underground", "uniform", "vacation", "vegetable", "vehicle",
  "victory", "village", "violence", "war", "wealth", "weapon", "weather", "wedding", "western", "wild",
  "winter", "wisdom", "wizard", "wood", "workshop", "writing", "zoo",
];
