/** A plain list of common English nouns, written for this project. Not the published game's card set. */
export const WORDS: readonly string[] = [
  "anchor", "apple", "arrow", "bank", "barrel", "bat", "beach", "bear", "bell", "belt",
  "bench", "bird", "blade", "board", "boat", "bolt", "bone", "book", "boot", "bottle",
  "bow", "box", "brain", "bread", "brick", "bridge", "brush", "bucket", "bug", "button",
  "cabin", "cake", "camera", "candle", "cannon", "cap", "car", "card", "carpet", "castle",
  "cat", "cave", "chain", "chair", "chalk", "cheese", "chest", "chicken", "church", "circle",
  "cliff", "clock", "cloud", "clown", "club", "coal", "coast", "coat", "coin", "comb",
  "compass", "cook", "copper", "corn", "cotton", "court", "cow", "crane", "cross", "crown",
  "cup", "curtain", "cycle", "dance", "deck", "desert", "diamond", "dice", "doctor", "dog",
  "doll", "dragon", "dress", "drill", "drum", "duck", "eagle", "earth", "egg", "engine",
  "eye", "fair", "fall", "fan", "farm", "feather", "fence", "field", "film", "fire",
  "fish", "flag", "flood", "floor", "flute", "fly", "fog", "foot", "forest", "fork",
  "fox", "frame", "frog", "fruit", "game", "garden", "gas", "gate", "ghost", "giant",
  "glass", "glove", "goat", "gold", "grass", "guitar", "hammer", "hand", "harbor", "hat",
  "heart", "helmet", "hill", "hole", "honey", "hook", "horn", "horse", "hospital", "hotel",
  "ice", "iron", "island", "jacket", "jam", "jar", "jet", "jewel", "judge", "key",
  "king", "kite", "knife", "knight", "knot", "ladder", "lake", "lamp", "lawn", "leaf",
  "lemon", "letter", "library", "light", "lion", "lock", "log", "magnet", "map", "mask",
  "match", "meadow", "medal", "milk", "mill", "mine", "mirror", "monkey", "moon", "mountain",
  "mouse", "mouth", "nail", "needle", "nest", "net", "night", "note", "nurse", "nut",
  "oar", "ocean", "oil", "onion", "orange", "organ", "oven", "owl", "paint", "palace",
  "palm", "pan", "paper", "park", "parrot", "path", "pearl", "pen", "pepper", "piano",
  "pie", "pig", "pillow", "pilot", "pin", "pipe", "pirate", "pitch", "plane", "plant",
  "plate", "pocket", "pole", "pool", "port", "pot", "pound", "press", "prince", "pyramid",
  "queen", "rabbit", "race", "rail", "rain", "rake", "rat", "ring", "river", "road",
  "robot", "rock", "rocket", "roof", "root", "rope", "rose", "ruler", "saddle", "sail",
  "salt", "sand", "saw", "scale", "school", "scissors", "screen", "seal", "seed", "shadow",
  "shark", "sheep", "shell", "ship", "shirt", "shoe", "shop", "shot", "shoulder", "shower",
  "sink", "skate", "ski", "sky", "slide", "smoke", "snake", "snow", "soap", "sock",
  "soldier", "soup", "spider", "sponge", "spoon", "spring", "spy", "square", "stable", "staff",
  "stage", "stamp", "star", "steam", "steel", "stick", "stone", "storm", "stove", "straw",
  "stream", "string", "sugar", "suit", "sun", "swamp", "sword", "table", "tail", "tank",
  "tape", "tea", "teacher", "telescope", "temple", "tent", "thief", "thread", "throne", "thumb",
  "ticket", "tie", "tiger", "toast", "tooth", "torch", "tower", "toy", "track", "train",
  "trap", "tree", "trip", "truck", "trunk", "tube", "tunnel", "turkey", "umbrella", "valley",
  "van", "vase", "village", "violin", "volcano", "wall", "watch", "water", "wave", "wax",
  "web", "well", "whale", "wheel", "whip", "whistle", "window", "wine", "wing", "wire",
  "witch", "wolf", "wood", "wool", "worm", "yard", "zebra", "zoo",
];
